webrick:
  headers:
    Access-Control-Allow-Origin: "*"

title: CV | Mohammad Ashrafuddin Ferdousi
description:  Polyglot Software Engineer. Solution designer. 10+ years experience in web domain. Expert on Laravel, Vuejs, Mysql.
url: 'https://codeperl.github.io'
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
